### PR TITLE
Biome colour and grass side tint options

### PR DESCRIPTION
**Pull request by jonkadelic**
This PR adds:
- Support for biome-based leaf and grass tinting, using the grasscolor.png and foliagecolor.png from Beta 1.7.3. The option for this will be disabled if both of these files are not present.
- Support for tinting the sides of grass blocks, as was added in Beta 1.5. This uses a patch to add the transparent grass side texture to [4, 5] on terrain.png, as well as a flag called "grass_sides_tint". If grass_sides_tint is not set to true in patch_data.txt, the option to enable side tinting will be disabled.

### CODE REVIEW

**Comment by iProgramMC** [comment]
Why not put `FoliageColor` and `GrassColor` into the client code? I mean the `World` project is shared between client and server (which doesn't yet exist but is going to at some point), and the server doesn't really need to know about colors now does it?

**Comment by jonkadelic** [comment]
Because FoliageColor and GrassColor both need to be referenced in `Tile`, which is in shared code. If FoliageColor and GrassColor were moved to client code it would break server builds.

**Comment by iProgramMC** [comment]
How about adding a `getTileColor` function into `TileRenderer` that returns either the advanced colors or the result of `Tile::getColor()`?

**Comment by jonkadelic** [comment]
OK, I've moved them into client/renderer/ using that strategy.

**Comment by iProgramMC** [comment]
BTW, the `c_` prefix in the patch data refers to Classic.

**Pull request merged**
