### PR TITLE
vcxproj file fixes

### PR DESCRIPTION
**Pull request by BrentDaMage**
* Platform version is now 8.1
* Platform toolset is now v141_xp
* Fixed IncludePath not inheriting default paths
* Disabled ConformanceMode since it causes the "IUnknown" issue on v141_xp

### CODE REVIEW

**Comment by BrentDaMage** [comment]
With these fixes, people can now use the build toolset provided in the Visual Studio Installer (v141_xp) to build for XP without using Visual Studio 2010.

**Comment by iProgramMC** [comment]
Please add a note saying that you have to change the build tools or go to "Individual components" in the VS installer and select the Windows XP build tools.

**Comment by BrentDaMage** [comment]
You want me to add that to the README?

**Comment by BrentDaMage** [comment]
This is going to be very apparent to the user if they don't have the toolset. Visual Studio will tell them this word-for-word. Perhaps just a quick little note of "If you don't have v141_xp installed, just change the build toolset to the latest available under the project's properties."

**Comment by iProgramMC** [comment]
Sure, but it isn't immediately obvious where to get the tools.  I couldn't figure that out for like 1 month, how will a novice do that?

**Comment by BrentDaMage** [comment]
No it is. You can find the answer pretty quickly via a simple Google search. In fact, it's the first result on Google for "v141_xp" and "visual studio windows xp" image 
image

**Comment by iProgramMC** [comment]
Hrm, I don't remember ever finding out from google, but fine. But do add the note anyways

**Comment by BrentDaMage** [comment]
I've updated the readme

**Pull request merged**
