### PR TITLE
fix raknet not being loaded

### PR DESCRIPTION
**Pull request by ljcool2006**

### CODE REVIEW

**Comment by BrentDaMage** [comment]
What version of Visual Studio and Windows were you using when you encountered this issue?

**Comment by ljcool2006** [comment]
> What version of Visual Studio and Windows were you using when you encountered this issue?

Visual Studio 2019, Windows 10

**Comment by iProgramMC** [comment]
I don't know what this does, other than removing a backslash. What kind of errors were you getting before this PR?

**Comment by iProgramMC** [comment]
Oops, fat finger mistake

**Comment by ljcool2006** [comment]
> I don't know what this does, other than removing a backslash. What kind of errors were you getting before this PR?

It couldn't find the directory when the backslash was present.

**Comment by iProgramMC** [comment]
Theoretically this shouldn't be a problem. IIRC Windows handles \\\\ in paths fine.

**Pull request merged**
