### PR TITLE
Add Direct Connect Button and Screen

### PR DESCRIPTION
**Pull request by uniformization**
Also added `build` and `dist` directories to the gitignore as they are used by the `build-wasm.sh` script.

### CODE REVIEW

**Comment by TheBrokenRail** [comment]
Does nobody read the first two commands of `build-wasm.sh`?

```sh
# Working Directory
mkdir -p wasm
cd wasm
```

*Everything* is stored in the `wasm` folder, which is already in `.gitignore`. If you have a `build` or `dist` folder in the repo's root, it's from something else.

**Comment by uniformization** [comment]
I was testing the script and I wrapped lines 5-25 of `build-wasm.sh` in an if condition, checking for the `emsdk` command (sine I didn't want to reinstall emsdk). I later decided just to remove that check I added but the `build` and `dist` directories in the gitignore were reminiscent. I'll remove them from the gitignore though.

**Comment by iProgramMC** [comment]
This does more than advertised - it also documents fields of the button class.

**Comment by iProgramMC** [comment]
Please test your pull requests before submitting them - I have to fix your errors now.

**Comment by uniformization** [comment]
> Please test your pull requests before submitting them - I have to fix your errors now.

That’s strange, it worked perfectly fine for me when I tested it on Windows.

**Comment by iProgramMC** [comment]
It did, but you have messed it up by using Hungarian notation and then forgetting to rename every instance of buttonId and text.

**Comment by uniformization** [comment]
> It did, but you have messed it up by using Hungarian notation and then forgetting to rename every instance of buttonId and text.

Looks like I already did that yesterday but it never committed for some reason
01qZs4jEO2

**Comment by iProgramMC** [comment]
Whoops. It's also my bad since I pulled without noticing, but, shit happens. It's fixed now anyways

**Pull request merged**
