### PR TITLE
ChatScreen (for players and local)

### PR DESCRIPTION
**Pull request by mqhirr**
I know @Gliese832B had a pull request of my modified ChatScreen but it is not up to date with the repo, so I made this pull req.

Here is a preview:
image

### CODE REVIEW

**Comment by iProgramMC** [comment]
Well, we already have a chat screen now.

**Comment by mqhirr** [comment]
alright

**Comment by iProgramMC** [comment]
It looks something like this:
image

I've also handled the server-side implementation and other stuff. Thanks for the idea though!

If you have other things you'd like to add, feel free :)

**Comment by mqhirr** [comment]
no problem!

**Pull request closed without merging**
